#!/usr/bin/env python3

"""clm5nl-gen - CLM5 namelist generator

Generates CLM5 namelists from  model parameters file and saves
the outputs to a specified directory. If no directory is
specified, the namelists are saved to the current directory.

Usage: 
  clm5nl-gen [--out DIR] PARAMFILE
  clm5nl-gen (-h | --help)
  clm5nl-gen (-v | --version)

Arguments:
  PARAMFILE           model parameters file (.yaml)

Options:
  -o DIR --out DIR    Save generated namelists to this directory.
  -h --help           Show this screen.
  -v --version        Show version.
"""
import sys
from pathlib import Path
from docopt import docopt
from ruamel.yaml import YAML
from clm5nl.generators import build_namelist

__version__ = "0.2-dev"
args = docopt(__doc__, version="clm5nl-gen v" + __version__)
invalid_args = False
params_file = Path(args["PARAMFILE"]).absolute()

# Validate input args
if (not params_file.exists()):
  print("clm5nl-gen error: Model parameter file '{}' not found.".format(params_file), file=sys.stderr)
  invalid_args = True

if (args["--out"] is None):
  out_dir = Path.cwd()
else:
  out_dir = Path(args["--out"]).absolute()
  if (not out_dir.is_dir()):
    print(f"Creating folder {out_dir}")
    out_dir.mkdir(parents=True, exist_ok=True)
print(f"Namelists will be saved to {out_dir}")
if invalid_args: sys.exit(-1)

# Parse model parameters file
yaml = YAML(typ='safe')
print(f"Reading model parameters file from {params_file}")
model_config = yaml.load(open(params_file, "r"))

ignored_sections = ["file_version"]
namelists = ["drv_in", "lnd_in", "drv_flds_in", "datm_in", "mosart_in", "modelio_nml"]
for section in model_config:
  if section in namelists:
    opts = {k:v for k, v in model_config[section].items()}
    build_namelist(section, opts, out_dir)
    namelists.remove(section)
  elif section in ignored_sections:
    pass
  else:
    print(f"WARNING: {section} is not recognized!")

# Namelists not mentioned in config file 
# should still be generated
for nl in namelists:
  build_namelist(nl, {}, out_dir)