[drv_in]
clm_start_type = "default"
stop_option = "date"
start_ymd = "2017-01-01"
stop_ymd = "2017-12-31"
#stop_n = 4
ntasks = 96

[lnd_in]
bgc_mode = "bgc"
clm_accelerated_spinup = "off"
l_ncpl = 48
lnd_frac = "${CESMDATAROOT}/domain.lnd.300x300_NRW_300x300_NRW.190619.nc"
lnd_tuning_mode = "clm5_0_CRUv7"
sim_year = "2000"
sim_year_range = "constant"

[lnd_in.user_nl]
# files
finidat = "${CESMDATAROOT}/FSpinup_300x300_NRW.clm2.r.2222-01-01-00000.nc"
fsnowaging = "${CESMDATAROOT}/snicar_drdt_bst_fit_60_c070416.nc"
fsnowoptics = "${CESMDATAROOT}/snicar_optics_5bnd_c090915.nc"
fsurdat = "${CESMDATAROOT}/surfdata_300x300_NRW_hist_78pfts_CMIP6_simyr2000_c190619.nc"
paramfile = "${CESMDATAROOT}/clm5_params.c171117.nc"
stream_fldfilename_ndep = "${CESMDATAROOT}/fndep_clm_hist_b.e21.BWHIST.f09_g17.CMIP6-historical-WACCM.ensmean_1849-2015_monthly_0.9x1.25_c180926.nc"
stream_fldfilename_popdens = "${CESMDATAROOT}/clmforc.Li_2017_HYDEv3.2_CMIP6_hdm_0.5x0.5_AVHRR_simyr1850-2016_c180202.nc"
stream_fldfilename_urbantv = "${CESMDATAROOT}/CLM50_tbuildmax_Oleson_2016_0.9x1.25_simyr1849-2106_c160923.nc"
stream_fldfilename_lightng = "${CESMDATAROOT}/clmforc.Li_2012_climo1995-2011.T62.lnfm_Total_c140423.nc"
stream_fldfilename_ch4finundated = "${CESMDATAROOT}/finundated_inversiondata_0.9x1.25_c170706.nc"

#clm_inparm:
co2_ppmv = 367.0
hist_empty_htapes = true
hist_fincl1 = ["TLAI","TSOI","TOTSOMC","TOTVEGC","TOTECOSYSC"]
hist_mfilt = 365
hist_nhtfrq = -24
use_init_interp = true

#urban
urban_hac = "ON_WASTEHEAT"
urban_traffic = false

[drv_flds_in]
megan_factors_file = "${CESMDATAROOT}/megan21_emis_factors_78pft_c20161108.nc"
  
[datm_in]
datm_mode = "CLMCRUNCEPv7"
datm_presaero = "clim_2010" # DATM prescribed aerosol forcing
domainfile = "${CESMDATAROOT}/domain.lnd.300x300_NRW_300x300_NRW.190619.nc"
stream_year_first = 2017    # first year of the stream data that will be used
stream_year_last = 2017     # last  year of the stream data that will be used
stream_year_align = 2017    # model year that will be aligned with stream data for year_first
stream_root_folder = "${CESMDATAROOT}/COSMOREA6/forcings"
stream_files = ["2017-01.nc", "2017-02.nc", "2017-03.nc", "2017-04.nc", "2017-05.nc"]