name: Download Wuestebach static files

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  WTB_REPO_NAME: "extpar_eclm_wuestebach_sp"
  WTB_REPO_TAG: 0.1

jobs:
  download_wtb_job:
    name: Download Wuestebach static files
    runs-on: ubuntu-24.04


    steps:
      - uses: actions/checkout@v4

      - name: Initialize git lfs
        run: |
          sudo apt-get update
          sudo apt-get install git-lfs
          git lfs install

      - name: Restore cached Wuestebach static files
        uses: actions/cache/restore@v4
        id: cache-wtb-restore
        with:
          path: ${{ github.workspace }}/${{ env.WTB_REPO_NAME }}
          key: ${{ env.WTB_REPO_NAME }}-${{ env.WTB_REPO_TAG }}

      - if: steps.cache-wtb-restore.outputs.cache-hit != 'true'
        name: Clone ${{ env.WTB_REPO_NAME }}
        working-directory: ${{ github.workspace }}
        run: |
          pwd
          time git clone -b ${WTB_REPO_TAG} https://icg4geo.icg.kfa-juelich.de/ExternalReposPublic/tsmp2-static-files/${WTB_REPO_NAME}.git
          du -ch ${WTB_REPO_NAME}

      - name: Check integrity of downloaded static files
        working-directory: ${{ github.workspace }}/${{ env.WTB_REPO_NAME }}
        run: |
          git lfs fsck

      - name: Save Wuestebach static files
        uses: actions/cache/save@v4
        id: cache-wtb-save
        with:
          path: ${{ github.workspace }}/${{ env.WTB_REPO_NAME }}
          key: ${{ env.WTB_REPO_NAME }}-${{ env.WTB_REPO_TAG }}

      - name: Show Wuestebach static files
        working-directory: ${{ github.workspace }}/${{ env.WTB_REPO_NAME }}
        run: |
          tree $(pwd)

