name: Download Wuestebach static files

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master


jobs:
  download_wtb_job:
    name: Download Wuestebach static files
    runs-on: ubuntu-24.04
    env:
      WTB_REPO_NAME: "extpar_eclm_wuestebach_sp"
      WTB_REPO_TAG: 0.1

    steps:
      - uses: actions/checkout@v4

      - name: Restore cached Wuestebach static files
        uses: actions/cache/restore@v4
        id: cache-wtb-restore
        with:
          path: ${{ github.workspace }}/${{ env.WTB_REPO_NAME }}
          key: ${{ env.WTB_REPO_NAME }}-${{ env.WTB_REPO_TAG }}
          lookup-only: true

      - if: steps.cache-wtb-restore.outputs.cache-hit != 'true'
        name: Clone ${{ env.WTB_REPO_NAME }}
        working-directory: ${{ github.workspace }}
        run: |
          git clone -b ${WTB_REPO_TAG} https://icg4geo.icg.kfa-juelich.de/ExternalReposPublic/tsmp2-static-files/${WTB_REPO_NAME}.git
          du -ch ${WTB_REPO_NAME}
          git lfs fsck
          tree $(pwd)

      - if: steps.cache-wtb-restore.outputs.cache-hit != 'true'
        name: Save Wuestebach static files
        uses: actions/cache/save@v4
        id: cache-wtb-save
        with:
          path: ${{ github.workspace }}/${{ env.WTB_REPO_NAME }}
          key: ${{ env.WTB_REPO_NAME }}-${{ env.WTB_REPO_TAG }}
