name: Run Resqui CI

on:
  push:

jobs:
  run-resqui:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run resqui action
        uses: EVERSE-ResearchSoftware/resqui-github-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          config: "configurations/basic.json"
