name: Check Fortran coding style

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    types:
      - ready_for_review

jobs:
  style-check:
    if: ${{ !github.event.pull_request.draft }}
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: 'pip'

      - name: Install pip packages
        run:  pip install fortitude-lint

      #TODO: Linter errors should be fixed one error code at a time (e.g. one error code per PR)
      - name: Check Fortran coding style
        continue-on-error: true
        run: fortitude check --statistics src

